name: qizhuang

server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.129:3306/qizhuangsite?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: qizhuang
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  jackson:
    serialization:
      indent_output: true

  data:
    mongodb:
      uri: mongodb://qizhuang:123456@192.168.182.129:27017/qizhuangsite

  rabbitmq:
    host: localhost
    port: 5672
    username: qizhuang
    password: 123456

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    #spring.redis.pool.max-active=8
    #spring.redis.pool.max-wait=-1
    #spring.redis.pool.max-idle=8
    #spring.redis.pool.min-idle=0
    timeout: 0