name: qizhuang

server:
  port: 80

mt4:
  port: 6217

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qizhuangsite?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: qizhuang
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  jackson:
    serialization:
      indent_output: true

  data:
    mongodb:
      uri: mongodb://qizhuang:123456@localhost:27017/qizhuangsite